export { default as CommentIcon } from './comment-icon'
export { default as ThumbsupIcon } from './thumbsup-icon'
export { default as ClockIcon } from './clock-icon'
export { default as SendIcon } from './send-icon'
export { default as RocketIcon } from './rocket-icon'
export { default as MagnifyingGlassIcon } from './magnifying-glass-icon'
export { default as MenuIcon } from './menu-icon'
export { default as BackIcon } from './back-icon'
