version: '3'
services:
  allhumor:
    container_name: allhumor
    restart: always
    build: .
    image: 1227800d434b
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - db
    links:
      - db
    tty: true
    
  db:
    image: mongo:latest
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"