export default {
  previewList: {
    REQUEST: 'previewList/REQUEST',
    SUCCESS: 'previewList/SUCCESS',
    ERROR: 'previewList/ERROR',
  },
  article: {
    REQUEST: 'article/REQUEST',
    SUCCESS: 'article/SUCCESS',
    ERROR: 'article/ERROR',
  },
  comment: {
    REQUEST: 'comment/REQUEST',
    SUCCESS: 'comment/SUCCESS',
    ERROR: 'comment/ERROR',
    ADD_REQUEST: 'comment/ADD_REQUEST',
    ADD_SUCCESS: 'comment/ADD_SUCCESS',
    ADD_ERROR: 'comment/ADD_ERROR',
    START_EDIT: 'comment/START_EDIT',
    FINISH_EDIT: 'comment/FINISH_EDIT',
    EDIT_REQUEST: 'comment/EDIT_REQUEST',
    EDIT_SUCCESS: 'comment/EDIT_SUCCESS',
    EDIT_ERROR: 'comment/EDIT_ERROR',
    REMOVE_REQUEST: 'comment/REMOVE_REQUEST',
    REMOVE_SUCCESS: 'comment/REMOVE_SUCCESS',
    REMOVE_ERROR: 'comment/REMOVE_ERROR',
    TOGGLE_EXPAND_TEXT: 'comment/TOGGLE_EXPAND_TEXT',
    START_ADD_REPLY: 'comment/START_ADD_REPLY',
    FINISH_ADD_REPLY: 'commment/FINISH_ADD_REPLY',
    ADD_REPLY_REQUEST: 'comment/ADD_REPLY_REQUEST',
    ADD_REPLY_SUCCESS: 'comment/ADD_REPLY_SUCCESS',
    ADD_REPLY_ERROR: 'comment/ADD_REPLY_ERROR',
    TOGGLE_EXPAND_REPLY: 'comment/TOGGLE_EXPAND_REPLY',
    REPLY_REQUEST: 'comment/REPLY_REQUEST',
    REPLY_SUCCESS: 'comment/REPLY_SUCCESS',
    REPLY_ERROR: 'comment/REPLY_ERROR',
  },
  voting: {
    REQUEST: 'voting/VOTING_REQUEST',
    ERROR: 'voting/VOTING_ERROR',
  },
  user: {
    SET_USER_PROFILE: 'user/SET_USER_PROFILE',
  },
  ui: {
    SWITCH_LOGIN_VIEW: 'ui/SWITCH_LOGIN_VIEW',
  },
  search: {
    REQUEST: 'search/SEARCH_REQUEST',
    SUCCESS: 'search/SEARCH_SUCCESS',
    ERROR: 'search/SEARCH_ERROR',
  },
}
